### ISSUE TITLE
Setup a service node on ec2

### ISSUE THREAD

**Issue by kulpreet** [ChluNetwork/chlu-ipfs-support#13]

**Comment by fazo96** [comment]
This is working, however we might need to setup a rendevouz server because we are using Websocket Star as an IPFS transport for Chlu, which requires a rendevouz server to act as relay between two peers. 

Now we are using a public one which is fine for testing but we might want to run our own and add it to the list of bootstrap nodes.

https://github.com/libp2p/js-libp2p-websocket-star-rendezvous

**Comment by kulpreet** [comment]
@fazo96 Let's create a new issue for setting up the rendezvous server, create a label 'production' and close this issue.

**Comment by fazo96** [comment]
Ok, closing this and moving redezvous server deployment to #17
