### ISSUE TITLE
On Demand start and stop IPFS

### ISSUE THREAD

**Issue by kulpreet** [ChluNetwork/chlu-ipfs-support#40]
I wonder if we can or should start and stop IPFS on demand?

For example, when a vendor has the wallet open, but there are no new transaction whose reviews have to be loaded, we can keep the IPFS disconnected, and then when a transaction comes, then we connect to IPFS and load the review and disconnect again.

Similarly for customer wallet. We need IPFS only when the customer is writing a new review.

What do you think @fazo96 ? Would that make sense or instead make things slower?

This will probably become more relevant when we want to provide chrome/firefox extensions. Keep IPFS always connected through the extension might create unnecessary network traffic, especially if in the future the DHT is release

**Comment by fazo96** [comment]
It makes sense to consider this, however starting IPFS is quite slow (a couple of seconds) most of which is spent connecting to the bootstrap nodes. The DHT will make things worse from this point of view but it can always be disabled: IPFS is turning into more of a collection of libp2p modules with an API on top so it can be tweaked easily.

The bandwidth hog of go-ipfs is caused by the DHT so by keeping it off we should be good.

Another interesting thing: bandwidth and storage stats just landed in js-ipfs master. This means soon we'll be able to measure this stuff :+1: 

If we ever implement starting/stopping IPFS as needed it will be quite hard if you have to run a lot of operations (for example you open the transaction history and you need to read a bunch of them) so we will have to figure out a "disconnect for inactivity" thing otherwise it would be super slow.

Since you mentioned the extension, there is https://github.com/ipfs-shipyard/ipfs-companion which lets browsers use the local IPFS gateway for ipfs.io URLs. The new version (not released yet) has a very interesting feature: instead of using a local go-ipfs gateway it runs js-ipfs inside the browser extension and can inject a `window.ipfs` object inside web pages, avoiding each app having its own js-ipfs instance. We might want to watch this as it could be very useful for Chlu.

As a plus, the extension should already be compatible with ChluIPFS since I knew about their `window.ipfs` idea from the start so I just used `window.ipfs` in our project and only created it if it's missing in the start procedure.

**Comment by fazo96** [comment]
The new marketplace lib and chlu-ipfs-support had some related work done: they now keep track of starting/stopping state so methods wait until the node is ready if it is still starting. The marketplace also autostarts the node if it's stopped when a method is called.

**Comment by fazo96** [comment]
This is fully implemented
